s pring:
  application:
    name: spring-data-jpa

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1244

  jpa:
    properties:
      hibernate:
        default_schema: blog
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: denemedenemecioglu8@gmail.com
    password: pkfxypnpugqqftxz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true



security:
  jwt:
    secret-key: "dGhlc2VjcmV0a2V5bXVzdGJldGhpc2xvbmcyNTZiaXRz"
    expiration-time: 3600000